"""
Project Context Core - Research project lifecycle management.

This bounded context handles:
- Creating and opening QualCoder projects (.qda files)
- Managing source files within projects
- Project navigation and switching
- Recent projects list
"""

from src.contexts.projects.core.derivers import (
    # Failure reasons
    DuplicateFolderName,
    DuplicateSourceName,
    EmptyProjectName,
    FolderNotEmpty,
    FolderNotFound,
    FolderState,
    InvalidFolderName,
    InvalidProjectPath,
    ParentNotWritable,
    ProjectAlreadyExists,
    ProjectNotFound,
    ProjectState,
    SourceFileNotFound,
    SourceNotFound,
    UnsupportedSourceType,
    derive_add_source,
    derive_create_folder,
    derive_create_project,
    derive_delete_folder,
    derive_move_source_to_folder,
    derive_open_project,
    derive_open_source,
    derive_remove_source,
    derive_rename_folder,
)
from src.contexts.projects.core.entities import (
    Folder,
    Project,
    ProjectId,
    ProjectSummary,
    RecentProject,
    Source,
    SourceStatus,
    SourceType,
)
from src.contexts.projects.core.events import (
    FolderCreated,
    FolderDeleted,
    FolderRenamed,
    NavigatedToSegment,
    ProjectClosed,
    ProjectCreated,
    ProjectOpened,
    ProjectRenamed,
    ScreenChanged,
    SourceAdded,
    SourceMovedToFolder,
    SourceOpened,
    SourceRemoved,
    SourceRenamed,
    SourceStatusChanged,
)
from src.contexts.projects.core.failure_events import (
    FolderNotCreated,
    FolderNotDeleted,
    FolderNotRenamed,
    ProjectNotCreated,
    ProjectNotOpened,
    SourceNotAdded,
    SourceNotMoved,
    SourceNotOpened,
    SourceNotRemoved,
    SourceNotUpdated,
)
from src.contexts.projects.core.invariants import (
    can_create_project,
    can_import_source,
    can_open_project,
    detect_source_type,
    is_source_name_unique,
    is_supported_source_type,
    is_valid_project_name,
    is_valid_project_path,
    is_valid_source_name,
)
from src.contexts.shared.core.types import FolderId

__all__ = [
    # Entities
    "Folder",
    "FolderId",
    "Project",
    "ProjectId",
    "ProjectSummary",
    "RecentProject",
    "Source",
    "SourceStatus",
    "SourceType",
    # Invariants
    "can_create_project",
    "can_import_source",
    "can_open_project",
    "detect_source_type",
    "is_source_name_unique",
    "is_supported_source_type",
    "is_valid_project_name",
    "is_valid_project_path",
    "is_valid_source_name",
    # Events
    "FolderCreated",
    "FolderDeleted",
    "FolderRenamed",
    "NavigatedToSegment",
    "ProjectClosed",
    "ProjectCreated",
    "ProjectOpened",
    "ProjectRenamed",
    "ScreenChanged",
    "SourceAdded",
    "SourceMovedToFolder",
    "SourceOpened",
    "SourceRemoved",
    "SourceRenamed",
    "SourceStatusChanged",
    # Derivers
    "FolderState",
    "ProjectState",
    "derive_add_source",
    "derive_create_folder",
    "derive_create_project",
    "derive_delete_folder",
    "derive_move_source_to_folder",
    "derive_open_project",
    "derive_open_source",
    "derive_remove_source",
    "derive_rename_folder",
    # Failure reasons (legacy - kept for backwards compatibility)
    "DuplicateFolderName",
    "DuplicateSourceName",
    "EmptyProjectName",
    "FolderNotEmpty",
    "FolderNotFound",
    "InvalidFolderName",
    "InvalidProjectPath",
    "ParentNotWritable",
    "ProjectAlreadyExists",
    "ProjectNotFound",
    "SourceFileNotFound",
    "SourceNotFound",
    "UnsupportedSourceType",
    # Failure events (new - publishable)
    "FolderNotCreated",
    "FolderNotDeleted",
    "FolderNotRenamed",
    "ProjectNotCreated",
    "ProjectNotOpened",
    "SourceNotAdded",
    "SourceNotMoved",
    "SourceNotOpened",
    "SourceNotRemoved",
    "SourceNotUpdated",
]
