"""
Qt Compatibility Layer - PySide6 bindings for QualCoder.

This module provides a unified import interface using PySide6 (LGPL license).

Usage:
    from design_system.qt_compat import (
        QWidget, QPushButton, QVBoxLayout,
        Signal, Slot, Property, Qt,
    )
"""

from __future__ import annotations

import os

# Configure pyqtgraph to use PySide6 before it's imported anywhere
os.environ.setdefault('PYQTGRAPH_QT_LIB', 'PySide6')

# PySide6 imports
from PySide6.QtWidgets import (
    QApplication,
    QMainWindow,
    QWidget,
    QDialog,
    QFrame,
    QLabel,
    QPushButton,
    QToolButton,
    QRadioButton,
    QCheckBox,
    QButtonGroup,
    QLineEdit,
    QTextEdit,
    QPlainTextEdit,
    QComboBox,
    QSpinBox,
    QDoubleSpinBox,
    QSlider,
    QProgressBar,
    QScrollArea,
    QScrollBar,
    QSplitter,
    QStackedWidget,
    QTabWidget,
    QTabBar,
    QToolBar,
    QStatusBar,
    QMenuBar,
    QMenu,
    QDockWidget,
    QListWidget,
    QListWidgetItem,
    QTreeWidget,
    QTreeWidgetItem,
    QTableWidget,
    QTableWidgetItem,
    QHeaderView,
    QAbstractItemView,
    QGraphicsView,
    QGraphicsScene,
    QGraphicsItem,
    QGraphicsRectItem,
    QGraphicsPolygonItem,
    QGraphicsEllipseItem,
    QGraphicsTextItem,
    QGraphicsPixmapItem,
    QGraphicsLineItem,
    QGraphicsPathItem,
    QGraphicsDropShadowEffect,
    QVBoxLayout,
    QHBoxLayout,
    QGridLayout,
    QFormLayout,
    QBoxLayout,
    QLayout,
    QSizePolicy,
    QSpacerItem,
    QMessageBox,
    QFileDialog,
    QInputDialog,
    QColorDialog,
    QFontDialog,
    QStyle,
    QStyleFactory,
    QStyleOption,
    QStyleOptionButton,
    QCompleter,
    QWidgetAction,
)

from PySide6.QtCore import (
    Qt,
    QObject,
    QSize,
    QPoint,
    QPointF,
    QRect,
    QRectF,
    QTimer,
    QThread,
    QMutex,
    QMutexLocker,
    QEventLoop,
    QPropertyAnimation,
    QParallelAnimationGroup,
    QSequentialAnimationGroup,
    QEasingCurve,
    QEvent,
    QMimeData,
    QUrl,
    QByteArray,
    QBuffer,
    QIODevice,
    QMargins,
    QMetaObject,
    QModelIndex,
    QAbstractItemModel,
    QAbstractTableModel,
    QAbstractListModel,
    QSortFilterProxyModel,
    QItemSelectionModel,
    QItemSelection,
    QRegularExpression,
    Signal,
    Slot,
    Property,
)

from PySide6.QtGui import (
    QAction,
    QIcon,
    QPixmap,
    QImage,
    QColor,
    QFont,
    QFontMetrics,
    QFontMetricsF,
    QPainter,
    QPen,
    QBrush,
    QPainterPath,
    QPolygon,
    QPolygonF,
    QTransform,
    QCursor,
    QKeySequence,
    QShortcut,
    QPalette,
    QGradient,
    QLinearGradient,
    QRadialGradient,
    QConicalGradient,
    QTextCursor,
    QTextDocument,
    QTextCharFormat,
    QTextBlockFormat,
    QSyntaxHighlighter,
    QClipboard,
    QDrag,
    QGuiApplication,
    QScreen,
    QDesktopServices,
    QTextFormat,
    QTextOption,
    QWheelEvent,
    QMouseEvent,
)

# Alias for compatibility
QSyntaxHighlighterGui = QSyntaxHighlighter

# Binding info
QT_BINDING = 'PySide6'
USING_PYSIDE6 = True


def get_qt_binding() -> str:
    """Return the name of the active Qt binding."""
    return QT_BINDING


def is_pyside6() -> bool:
    """Check if PySide6 is the active binding."""
    return True


# Export everything for easy importing
__all__ = [
    # Binding info
    'QT_BINDING',
    'USING_PYSIDE6',
    'get_qt_binding',
    'is_pyside6',

    # Signal/Slot
    'Signal',
    'Slot',
    'Property',

    # QtWidgets
    'QApplication',
    'QMainWindow',
    'QWidget',
    'QDialog',
    'QFrame',
    'QLabel',
    'QPushButton',
    'QToolButton',
    'QRadioButton',
    'QCheckBox',
    'QButtonGroup',
    'QLineEdit',
    'QTextEdit',
    'QPlainTextEdit',
    'QComboBox',
    'QSpinBox',
    'QDoubleSpinBox',
    'QSlider',
    'QProgressBar',
    'QScrollArea',
    'QScrollBar',
    'QSplitter',
    'QStackedWidget',
    'QTabWidget',
    'QTabBar',
    'QToolBar',
    'QStatusBar',
    'QMenuBar',
    'QMenu',
    'QDockWidget',
    'QListWidget',
    'QListWidgetItem',
    'QTreeWidget',
    'QTreeWidgetItem',
    'QTableWidget',
    'QTableWidgetItem',
    'QHeaderView',
    'QAbstractItemView',
    'QGraphicsView',
    'QGraphicsScene',
    'QGraphicsItem',
    'QGraphicsRectItem',
    'QGraphicsPolygonItem',
    'QGraphicsEllipseItem',
    'QGraphicsTextItem',
    'QGraphicsPixmapItem',
    'QGraphicsLineItem',
    'QGraphicsPathItem',
    'QGraphicsDropShadowEffect',
    'QVBoxLayout',
    'QHBoxLayout',
    'QGridLayout',
    'QFormLayout',
    'QBoxLayout',
    'QLayout',
    'QSizePolicy',
    'QSpacerItem',
    'QMessageBox',
    'QFileDialog',
    'QInputDialog',
    'QColorDialog',
    'QFontDialog',
    'QStyle',
    'QStyleFactory',
    'QStyleOption',
    'QStyleOptionButton',
    'QCompleter',
    'QWidgetAction',

    # QtCore
    'Qt',
    'QObject',
    'QSize',
    'QPoint',
    'QPointF',
    'QRect',
    'QRectF',
    'QTimer',
    'QThread',
    'QMutex',
    'QMutexLocker',
    'QEventLoop',
    'QPropertyAnimation',
    'QParallelAnimationGroup',
    'QSequentialAnimationGroup',
    'QEasingCurve',
    'QEvent',
    'QMimeData',
    'QUrl',
    'QByteArray',
    'QBuffer',
    'QIODevice',
    'QMargins',
    'QMetaObject',
    'QModelIndex',
    'QAbstractItemModel',
    'QAbstractTableModel',
    'QAbstractListModel',
    'QSortFilterProxyModel',
    'QItemSelectionModel',
    'QItemSelection',
    'QRegularExpression',

    # QtGui
    'QAction',
    'QIcon',
    'QPixmap',
    'QImage',
    'QColor',
    'QFont',
    'QFontMetrics',
    'QFontMetricsF',
    'QPainter',
    'QPen',
    'QBrush',
    'QPainterPath',
    'QPolygon',
    'QPolygonF',
    'QTransform',
    'QCursor',
    'QKeySequence',
    'QShortcut',
    'QPalette',
    'QGradient',
    'QLinearGradient',
    'QRadialGradient',
    'QConicalGradient',
    'QTextCursor',
    'QTextDocument',
    'QTextCharFormat',
    'QTextBlockFormat',
    'QSyntaxHighlighter',
    'QSyntaxHighlighterGui',
    'QClipboard',
    'QDrag',
    'QGuiApplication',
    'QScreen',
    'QDesktopServices',
    'QTextFormat',
    'QTextOption',
    'QWheelEvent',
    'QMouseEvent',
]
